"""P0-B V4-r9.3 Windows Service Authority Implementation with IPC.

F14 V4-r9.3 FIX: Complete functional authority implementation with real key loading and CERTIFY.

Architecture:
    AUTHORITY SERVICE (LocalService / gMSA)
        ↓
    Service Identity != User Identity
        ↓
    Private Key Storage (Service-scoped with DPAPI)
        ↓
    Named Pipe (Service endpoint with ACL)
        ↓
    Authorized Caller Check (Service validates caller SID)
        ↓
    CERTIFY operation (real signature generation)

Security Model:
- Authority runs under dedicated service identity (LocalService or gMSA)
- Private key stored in service-scoped location with DPAPI (service identity)
- Named Pipe ACL restricted to authorized callers
- Service process isolation prevents same-user key access
- IPC validates caller SID before authorizing operations
- Fail-closed behavior for missing/corrupted keys

Threat Model:
- T3 (same-user attacker): Protected by service identity boundary
- Private key: Only accessible to service identity
- IPC: Pipe ACL restricts to authorized callers
- Caller SID validation prevents unauthorized IPC invocation

Deployment Requirements:
- Administrator privileges for service installation
- pywin32 service framework
- Service configuration (name, display name, start type)
- Service-managed key storage location
- Named Pipe server implementation
- Caller SID validation
- Authority key provisioning (admin only)

Note: This module provides the complete functional authority implementation.
Service installation requires running as Administrator via service manager.
"""

from __future__ import annotations

import json
import logging
import sys
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Windows Service support
try:
    import win32service
    import win32serviceutil
    import win32event
    import win32api
    import win32security
    import win32pipe
    import win32file
    import win32con
    import pywintypes
    import servicemanager
    WINDOWS_SERVICE_AVAILABLE = True
except ImportError:
    WINDOWS_SERVICE_AVAILABLE = False

# Cryptography support
try:
    from cryptography.hazmat.primitives.asymmetric import ed25519
    from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, PublicFormat, NoEncryption
    CRYPTOGRAPHY_AVAILABLE = True
except ImportError:
    CRYPTOGRAPHY_AVAILABLE = False

# JSON support
import json

# DPAPI support
try:
    import win32crypt
    DPAPI_AVAILABLE = True
except ImportError:
    DPAPI_AVAILABLE = False

logger = logging.getLogger(__name__)


class AuthorityKeyError(Exception):
    """Raised when authority key operations fail."""
    pass


class AuthorityServiceIPCError(Exception):
    """Raised when IPC operation fails."""
    pass


class AuthorityServiceAuthorizationError(Exception):
    """Raised when caller is not authorized."""
    pass


class AuthorityKeyManager:
    """Service-scoped authority key management.
    
    F14 V4-r9.4 FIX: Real authority key loading and management with service-identity DPAPI.
    
    This class provides:
    - Service-scoped key storage (C:\ProgramData\IABV\authority_keys\)
    - DPAPI protection with service identity (key generated by service, not Administrator)
    - Key loading with fail-closed behavior
    - Identity verification
    - Provisioning via protected flag file (not user-controllable environment variable)
    
    CRITICAL: generate_and_store_key() must be called from the service process itself
    (running under LocalService), not from an Administrator PowerShell. This ensures
    the DPAPI blob is protected under the correct identity.
    
    SECURITY: Provisioning is controlled by a flag file in C:\ProgramData\IABV\
    that only Administrators can create/modify. Normal users cannot enable provisioning.
    """
    
    def __init__(
        self,
        key_storage_path: Path,
        service_identity: str = "LocalService",
        program_data_path: Path | None = None,
    ):
        """Initialize authority key manager.
        
        Args:
            key_storage_path: Path to service-scoped key storage
            service_identity: Service identity (LocalService, etc.)
            program_data_path: Path to C:\ProgramData\IABV for provisioning flag
        """
        if not DPAPI_AVAILABLE:
            raise AuthorityKeyError(
                "Authority key management requires Windows DPAPI (win32crypt). "
                "This platform is not supported for production authority."
            )
        
        if not CRYPTOGRAPHY_AVAILABLE:
            raise AuthorityKeyError(
                "Authority key management requires cryptography. "
                "Install with: pip install cryptography"
            )
        
        self.key_storage_path = key_storage_path
        self.service_identity = service_identity
        self.program_data_path = program_data_path or Path("C:\\ProgramData\\IABV")
        self._private_key: ed25519.Ed25519PrivateKey | None = None
        self._public_key: ed25519.Ed25519PublicKey | None = None
        self._key_id: str | None = None
        
        logger.info("AuthorityKeyManager initialized: %s", key_storage_path)
    
    def _is_provisioning_enabled(self) -> bool:
        """Check if provisioning is enabled via protected flag file.
        
        SECURITY: This checks for a flag file in C:\ProgramData\IABV\.
        Only Administrators can create/modify files in C:\ProgramData\.
        Normal users cannot enable provisioning by setting this flag.
        
        Returns:
            True if provisioning flag exists, False otherwise
        """
        provisioning_flag = self.program_data_path / "AUTHORITY_PROVISIONING_ENABLED"
        return provisioning_flag.exists()
    
    def _get_key_file_path(self) -> Path:
        """Get path to authority private key file."""
        return self.key_storage_path / "authority_private_key.json"
    
    def generate_and_store_key(self) -> tuple[str, str]:
        """Generate and store new authority key pair.
        
        F14 V4-r9.4 FIX: Generate key in service context with DPAPI protection.
        
        CRITICAL: This method must be called from the service process itself
        (running under LocalService), NOT from an Administrator PowerShell. The
        DPAPI blob will be protected under the identity of the calling process.
        If called from Administrator, the key will be protected under Administrator
        and the service (LocalService) will not be able to decrypt it.
        
        This should be called only during authorized provisioning, where the service
        is started with allow_provisioning=True to generate its key under its
        own identity.
        
        Returns:
            (key_id, public_key_hex)
        
        Raises:
            AuthorityKeyError: If key generation or storage fails
        """
        # Generate Ed25519 key pair
        private_key = ed25519.Ed25519PrivateKey.generate()
        public_key = private_key.public_key()
        
        # Extract key bytes
        private_key_bytes = private_key.private_bytes(
            Encoding.Raw,
            PrivateFormat.Raw,
            NoEncryption()
        )
        
        public_key_bytes = public_key.public_bytes(Encoding.Raw, PublicFormat.Raw)
        
        # Protect private key with DPAPI
        # This encrypts the key under the current process identity
        # If called from LocalService, only LocalService can decrypt
        # If called from Administrator, only Administrator can decrypt
        try:
            protected_result = win32crypt.CryptProtectData(
                private_key_bytes,
                None,
                None,
                None,
                None,
                0
            )
            protected_bytes = protected_result if not isinstance(protected_result, tuple) else protected_result[0]
            protected_key_hex = protected_bytes.hex()
        except Exception as exc:
            raise AuthorityKeyError(f"DPAPI protection failed: {exc}")
        
        # Compute key ID
        key_id = public_key_bytes.hex()[:16]
        public_key_hex = public_key_bytes.hex()
        
        # Store key data
        key_data = {
            "key_id": key_id,
            "public_key_hex": public_key_hex,
            "private_key_protected": protected_key_hex,
            "protection": "DPAPI",
            "service_identity": self.service_identity,
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "dpapi_identity_warning": "This key is protected under the identity of the process that called generate_and_store_key(). If called from Administrator, LocalService cannot decrypt it.",
        }
        
        key_file = self._get_key_file_path()
        try:
            key_file.parent.mkdir(parents=True, exist_ok=True)
            with open(key_file, 'w', encoding='utf-8') as f:
                json.dump(key_data, f, indent=2)
            logger.info("Generated and stored authority key: %s (protected under current process identity)", key_id)
        except Exception as exc:
            raise AuthorityKeyError(f"Key storage failed: {exc}")
        
        return key_id, public_key_hex
    
    def load_key(self) -> None:
        """Load authority key from storage.
        
        F14 V4-r9.4 FIX: Load key with DPAPI unprotection and fail-closed behavior.
        
        If provisioning flag exists in C:\ProgramData\IABV\ and key is missing,
        generates key under current identity. Flag can only be created by Administrator.
        If provisioning flag does not exist (normal runtime), fails closed if key is missing.
        
        Raises:
            AuthorityKeyError: If key missing, corrupted, or inaccessible
        """
        key_file = self._get_key_file_path()
        
        # Check if key file exists
        if not key_file.exists():
            if self._is_provisioning_enabled():
                logger.warning("Authority key not found, provisioning under current process identity: %s", key_file)
                logger.warning("Provisioning flag exists in C:\\ProgramData\\IABV\\ - assuming authorized provisioning")
                self.generate_and_store_key()
                # Reload after generation
                return self.load_key()
            else:
                raise AuthorityKeyError(
                    f"Authority key file not found: {key_file}. "
                    "Authority cannot operate without a valid key. "
                    "Provisioning must create the key first via AUTHORITY_PROVISIONING_ENABLED flag."
                )
        
        # Load key data
        try:
            with open(key_file, 'r', encoding='utf-8') as f:
                key_data = json.load(f)
        except json.JSONDecodeError as exc:
            raise AuthorityKeyError(f"Key file corrupted (invalid JSON): {exc}")
        except Exception as exc:
            raise AuthorityKeyError(f"Key file load failed: {exc}")
        
        # Validate key data structure
        required_fields = ["key_id", "public_key_hex", "private_key_protected", "protection"]
        for field in required_fields:
            if field not in key_data:
                raise AuthorityKeyError(f"Key file missing required field: {field}")
        
        # Verify protection mechanism
        if key_data["protection"] != "DPAPI":
            raise AuthorityKeyError(
                f"Unsupported protection mechanism: {key_data['protection']}. "
                "Only DPAPI is supported."
            )
        
        # Unprotect private key with DPAPI
        # This will fail if the current process identity doesn't match the protection identity
        try:
            encrypted_bytes = bytes.fromhex(key_data["private_key_protected"])
            decrypted = win32crypt.CryptUnprotectData(encrypted_bytes, None, None, None)
            
            if isinstance(decrypted, tuple):
                decrypted_bytes = decrypted[1]
            else:
                decrypted_bytes = decrypted
            
            if len(decrypted_bytes) != 32:
                raise AuthorityKeyError(
                    f"Decrypted key has invalid length: {len(decrypted_bytes)} (expected 32)"
                )
            
            # Reconstruct private key
            self._private_key = ed25519.Ed25519PrivateKey.from_private_bytes(decrypted_bytes)
            self._public_key = self._private_key.public_key()
            self._key_id = key_data["key_id"]
            
            # Verify public key matches
            expected_public_key_hex = self._public_key.public_bytes(Encoding.Raw, PublicFormat.Raw).hex()
            if expected_public_key_hex != key_data["public_key_hex"]:
                raise AuthorityKeyError(
                    "Public key mismatch in key file. "
                    "Key file may have been tampered with."
                )
            
            logger.info("Loaded authority key: %s", self._key_id)
            
        except AuthorityKeyError:
            raise
        except Exception as exc:
            raise AuthorityKeyError(
                f"DPAPI unprotection failed: {exc}. "
                "This typically means the key was protected under a different identity "
                "than the current process. Ensure the key was generated by the service "
                "running under the intended identity (LocalService)."
            )
    
    def sign_canonical(self, canonical_bytes: bytes) -> str:
        """Sign canonical data with authority private key.
        
        F14 V4-r9.3 FIX: Actual signing operation.
        
        Args:
            canonical_bytes: Canonical data to sign
            
        Returns:
            Hex string of Ed25519 signature
            
        Raises:
            AuthorityKeyError: If key not loaded or signing fails
        """
        if self._private_key is None:
            raise AuthorityKeyError("Authority key not loaded. Call load_key() first.")
        
        try:
            signature = self._private_key.sign(canonical_bytes)
            return signature.hex()
        except Exception as exc:
            raise AuthorityKeyError(f"Signing failed: {exc}")
    
    def get_public_key_hex(self) -> str:
        """Get authority public key hex.
        
        Returns:
            Hex string of public key
            
        Raises:
            AuthorityKeyError: If key not loaded
        """
        if self._public_key is None:
            raise AuthorityKeyError("Authority key not loaded. Call load_key() first.")
        
        return self._public_key.public_bytes(Encoding.Raw, PublicFormat.Raw).hex()
    
    def get_key_id(self) -> str:
        """Get authority key ID.
        
        Returns:
            Key ID string
            
        Raises:
            AuthorityKeyError: If key not loaded
        """
        if self._key_id is None:
            raise AuthorityKeyError("Authority key not loaded. Call load_key() first.")
        
        return self._key_id


class AuthorityNamedPipeServer:
    """Named Pipe server for authority IPC.
    
    F14 V4-r9.2 FIX: Named Pipe server with caller SID validation.
    
    This class implements the Named Pipe server that:
    - Creates Named Pipe with restrictive ACL
    - Validates caller SID before processing requests
    - Handles CERTIFY operations
    - Prevents unauthorized key access
    """
    
    def __init__(
        self,
        pipe_name: str = r"\\.\pipe\IABVAuditAuthority",
        authorized_sids: list[str] | None = None,
        key_manager: AuthorityKeyManager | None = None,
    ):
        """Initialize Named Pipe server.
        
        F14 V4-r9.3 FIX: Add key manager for actual CERTIFY operations.
        
        Args:
            pipe_name: Named Pipe name
            authorized_sids: List of authorized SIDs (if None, allows current user)
            key_manager: Authority key manager for signing operations
        """
        if not WINDOWS_SERVICE_AVAILABLE:
            raise RuntimeError("Named Pipe server requires pywin32")
        
        self.pipe_name = pipe_name
        self.authorized_sids = authorized_sids or []
        self._key_manager = key_manager
        self._running = False
        self._server_thread = None
        self._stop_event = threading.Event()
        
        # F14 V4-r9.2 FIX: Load caller SID if not provided
        if not self.authorized_sids:
            try:
                token = win32security.OpenThreadToken(
                    win32api.GetCurrentThread(),
                    win32security.TOKEN_QUERY,
                    True
                )
                sid = win32security.GetTokenInformation(token, win32security.TokenUser)[0]
                self.authorized_sids.append(str(sid))
                logger.info("Authorized caller SID: %s", sid)
            except Exception as exc:
                logger.warning("Failed to get current user SID: %s", exc)
        
        logger.info("AuthorityNamedPipeServer initialized: %s", pipe_name)
    
    def _create_pipe_security_descriptor(self) -> win32security.SECURITY_DESCRIPTOR:
        """Create security descriptor for Named Pipe.
        
        F14 V4-r9.2 FIX: Restrict pipe access to authorized callers only.
        
        Returns:
            Security descriptor with restrictive ACL
        """
        # Create security descriptor
        sd = win32security.SECURITY_DESCRIPTOR()
        sd.SetSecurityDescriptorOwner(win32security.GetCurrentUserSid(), False)
        
        # Create DACL
        dacl = win32security.ACL()
        
        # Allow LocalService (owner) full control
        try:
            local_service_sid = win32security.ConvertStringSidToSid("S-1-5-19")
            dacl.AddAccessAllowedAce(
                win32security.ACL_REVISION,
                win32con.FILE_ALL_ACCESS,
                local_service_sid
            )
        except Exception as exc:
            logger.warning("Failed to add LocalService to DACL: %s", exc)
        
        # Allow authorized callers read/write
        for sid_str in self.authorized_sids:
            try:
                sid = win32security.ConvertStringSidToSid(sid_str)
                dacl.AddAccessAllowedAce(
                    win32security.ACL_REVISION,
                    win32con.GENERIC_READ | win32con.GENERIC_WRITE,
                    sid
                )
                logger.info("Added authorized SID to DACL: %s", sid_str)
            except Exception as exc:
                logger.warning("Failed to add SID %s to DACL: %s", sid_str, exc)
        
        # Deny Everyone (fail-closed)
        try:
            everyone_sid = win32security.ConvertStringSidToSid("S-1-1-0")
            dacl.AddAccessDeniedAce(
                win32security.ACL_REVISION,
                win32con.FILE_ALL_ACCESS,
                everyone_sid
            )
        except Exception as exc:
            logger.warning("Failed to deny Everyone: %s", exc)
        
        sd.SetSecurityDescriptorDacl(1, dacl, 0)
        return sd
    
    def _validate_caller_sid(self, client_handle) -> str:
        """Validate caller SID.
        
        F14 V4-r9.2 FIX: Verify caller is authorized before processing request.
        
        Args:
            client_handle: Client pipe handle
            
        Returns:
            Caller SID string
            
        Raises:
            AuthorityServiceAuthorizationError: If caller not authorized
        """
        try:
            # Get client process ID
            client_pid = win32pipe.GetNamedPipeClientProcessId(client_handle)
            
            # Get process token
            process_handle = win32api.OpenProcess(
                win32con.PROCESS_QUERY_INFORMATION,
                False,
                client_pid
            )
            
            try:
                token = win32security.OpenProcessToken(
                    process_handle,
                    win32security.TOKEN_QUERY
                )
                
                try:
                    # Get user SID
                    user_sid = win32security.GetTokenInformation(token, win32security.TokenUser)[0]
                    sid_str = str(user_sid)
                    
                    # Validate against authorized SIDs
                    if self.authorized_sids and sid_str not in self.authorized_sids:
                        raise AuthorityServiceAuthorizationError(
                            f"Caller SID {sid_str} not in authorized list"
                        )
                    
                    logger.info("Authorized caller SID: %s", sid_str)
                    return sid_str
                    
                finally:
                    win32api.CloseHandle(token)
            finally:
                win32api.CloseHandle(process_handle)
                
        except AuthorityServiceAuthorizationError:
            raise
        except Exception as exc:
            logger.error("Failed to validate caller SID: %s", exc)
            raise AuthorityServiceAuthorizationError(f"Caller SID validation failed: {exc}")
    
    def _handle_certify_request(self, request: dict[str, Any]) -> dict[str, Any]:
        """Handle CERTIFY request.
        
        F14 V4-r9.3 FIX: Real certification with authority signature.
        
        Args:
            request: CERTIFY request dictionary
            
        Returns:
            Response dictionary with signature
            
        Raises:
            AuthorityServiceIPCError: If certification fails
        """
        if self._key_manager is None:
            raise AuthorityServiceIPCError(
                "Authority key manager not configured. "
                "Service cannot sign without a loaded key."
            )
        
        if "audit_record" not in request:
            raise AuthorityServiceIPCError("Missing audit_record in CERTIFY request")
        
        audit_record = request["audit_record"]
        
        # Validate audit record structure
        if not isinstance(audit_record, dict):
            raise AuthorityServiceIPCError("audit_record must be a dictionary")
        
        # Extract required fields for signing
        # F14 V4-r9.3 FIX: Sign the canonical representation of the audit record
        try:
            # Create canonical representation
            canonical = json.dumps(audit_record, sort_keys=True, separators=(',', ':'), ensure_ascii=False).encode('utf-8')
            
            # Sign with authority private key
            signature_hex = self._key_manager.sign_canonical(canonical)
            
            # Build response
            response = {
                "status": "certified",
                "signature": signature_hex,
                "key_id": self._key_manager.get_key_id(),
                "public_key_hex": self._key_manager.get_public_key_hex(),
                "certified_at_utc": datetime.now(timezone.utc).isoformat(),
            }
            
            logger.info("CERTIFY operation completed for audit record")
            return response
            
        except AuthorityKeyError as exc:
            raise AuthorityServiceIPCError(f"Authority key error: {exc}")
        except Exception as exc:
            raise AuthorityServiceIPCError(f"Certification failed: {exc}")
    
    def _handle_request(self, request: dict[str, Any], client_handle) -> dict[str, Any]:
        """Handle IPC request.
        
        F14 V4-r9.3 FIX: Validate caller and route to operation handler.
        
        Args:
            request: Request dictionary
            client_handle: Client pipe handle
            
        Returns:
            Response dictionary
        """
        # Validate caller SID
        caller_sid = self._validate_caller_sid(client_handle)
        
        # Route to operation handler
        operation = request.get("operation")
        
        if operation == "CERTIFY":
            return self._handle_certify_request(request)
        elif operation == "STATUS":
            return {
                "status": "running",
                "service": "IABVAuditAuthority",
                "caller_sid": caller_sid,
            }
        elif operation == "GET_PUBLIC_KEY":
            return self._handle_get_public_key_request()
        elif operation == "HEALTH":
            return self._handle_health_request()
        else:
            raise AuthorityServiceIPCError(f"Unknown operation: {operation}")
    
    def _handle_get_public_key_request(self) -> dict[str, Any]:
        """Handle GET_PUBLIC_KEY request.
        
        F14 V4-r9.3 FIX: Return authority public key.
        
        Returns:
            Response dictionary with public key
            
        Raises:
            AuthorityServiceIPCError: If key not loaded
        """
        if self._key_manager is None:
            raise AuthorityServiceIPCError(
                "Authority key manager not configured."
            )
        
        try:
            return {
                "status": "success",
                "key_id": self._key_manager.get_key_id(),
                "public_key_hex": self._key_manager.get_public_key_hex(),
            }
        except AuthorityKeyError as exc:
            raise AuthorityServiceIPCError(f"Failed to get public key: {exc}")
    
    def _handle_health_request(self) -> dict[str, Any]:
        """Handle HEALTH request.
        
        F14 V4-r9.3 FIX: Return service health status.
        
        Returns:
            Response dictionary with health status
        """
        key_loaded = self._key_manager is not None
        key_id = self._key_manager.get_key_id() if key_loaded else None
        
        return {
            "status": "healthy" if key_loaded else "degraded",
            "service": "IABVAuditAuthority",
            "key_loaded": key_loaded,
            "key_id": key_id,
        }
    
    def _client_handler(self, client_handle):
        """Handle client connection.
        
        F14 V4-r9.2 FIX: Process client requests with authorization.
        
        Args:
            client_handle: Client pipe handle
        """
        try:
            while not self._stop_event.is_set():
                try:
                    # Read request
                    result, data = win32file.ReadFile(client_handle, 4096, None)
                    if not data:
                        break
                    
                    request = json.loads(data.decode('utf-8'))
                    logger.info("Received request: %s", request.get("operation"))
                    
                    # Handle request
                    response = self._handle_request(request, client_handle)
                    
                    # Write response
                    response_data = json.dumps(response).encode('utf-8')
                    win32file.WriteFile(client_handle, response_data, None)
                    
                except win32api.error as exc:
                    if exc.winerror == 109:  # Broken pipe
                        break
                    logger.error("Client handler error: %s", exc)
                    break
                except Exception as exc:
                    logger.error("Request processing error: %s", exc)
                    # Send error response
                    error_response = {"error": str(exc)}
                    try:
                        response_data = json.dumps(error_response).encode('utf-8')
                        win32file.WriteFile(client_handle, response_data, None)
                    except:
                        pass
                    break
                    
        finally:
            win32file.CloseHandle(client_handle)
            logger.info("Client handler terminated")
    
    def _server_loop(self):
        """Main server loop.
        
        F14 V4-r9.2 FIX: Accept client connections and spawn handlers.
        """
        logger.info("Named Pipe server loop started")
        
        while not self._stop_event.is_set():
            try:
                # Create Named Pipe
                sd = self._create_pipe_security_descriptor()
                sa = win32security.SECURITY_ATTRIBUTES()
                sa.SetSecurityDescriptor(sd)
                
                pipe_handle = win32pipe.CreateNamedPipe(
                    self.pipe_name,
                    win32pipe.PIPE_ACCESS_DUPLEX,
                    win32pipe.PIPE_TYPE_MESSAGE | win32pipe.PIPE_READMODE_MESSAGE | win32pipe.PIPE_WAIT,
                    win32pipe.PIPE_UNLIMITED_INSTANCES,
                    4096,
                    4096,
                    0,
                    sa
                )
                
                logger.info("Named Pipe created: %s", self.pipe_name)
                
                # Wait for client connection
                win32pipe.ConnectNamedPipe(pipe_handle, None)
                logger.info("Client connected")
                
                # Spawn client handler in thread
                client_thread = threading.Thread(
                    target=self._client_handler,
                    args=(pipe_handle,)
                )
                client_thread.daemon = True
                client_thread.start()
                
            except win32api.error as exc:
                if exc.winerror == 232:  # Pipe is being closed
                    break
                logger.error("Named Pipe server error: %s", exc)
                if not self._stop_event.is_set():
                    # Retry after delay
                    self._stop_event.wait(1)
            except Exception as exc:
                logger.error("Named Pipe server error: %s", exc)
                if not self._stop_event.is_set():
                    self._stop_event.wait(1)
        
        logger.info("Named Pipe server loop terminated")
    
    def start(self):
        """Start Named Pipe server.
        
        F14 V4-r9.2 FIX: Start server in background thread.
        """
        if self._running:
            logger.warning("Named Pipe server already running")
            return
        
        self._running = True
        self._stop_event.clear()
        self._server_thread = threading.Thread(target=self._server_loop)
        self._server_thread.daemon = True
        self._server_thread.start()
        
        logger.info("Named Pipe server started")
    
    def stop(self):
        """Stop Named Pipe server.
        
        F14 V4-r9.2 FIX: Stop server gracefully.
        """
        if not self._running:
            return
        
        self._running = False
        self._stop_event.set()
        
        if self._server_thread:
            self._server_thread.join(timeout=5)
        
        logger.info("Named Pipe server stopped")


class AuthorityWindowsService:
    """Windows Service wrapper for audit authority.
    
    F14 V4-r9 FIX: Authority runs as Windows Service with dedicated identity.
    
    This class provides the service architecture for running the audit authority
    as a Windows Service with a dedicated identity (LocalService or gMSA).
    
    The service:
    - Runs under dedicated service identity (separate from normal user)
    - Stores private key in service-scoped location
    - Exposes Named Pipe endpoint with ACL restriction
    - Validates caller identity before authorizing operations
    
    Deployment:
    - Requires Administrator privileges for installation
    - Requires pywin32 service framework
    - Service configuration managed via Windows Service Control Manager
    """
    
    def __init__(
        self,
        service_name: str = "IABVAuditAuthority",
        service_display_name: str = "IABV Audit Authority Service",
        service_description: str = "Cryptographic audit authority for IABV provenance verification",
    ):
        """Initialize Windows Service configuration.
        
        Args:
            service_name: Internal service name
            service_display_name: Display name in Service Manager
            service_description: Service description
        """
        if not WINDOWS_SERVICE_AVAILABLE:
            raise RuntimeError(
                "Windows Service support requires pywin32. "
                "Install with: pip install pywin32"
            )
        
        if sys.platform != "win32":
            raise RuntimeError(
                "Windows Service is only supported on Windows platform."
            )
        
        self.service_name = service_name
        self.service_display_name = service_display_name
        self.service_description = service_description
        
        logger.info("AuthorityWindowsService configured: %s", service_name)
    
    def get_service_identity(self) -> str:
        """Get the service identity (should be LocalService or gMSA).
        
        F14 V4-r9 FIX: Service identity is different from normal user identity.
        
        Returns:
            Service identity string (e.g., "LocalService", "NT AUTHORITY\\LocalService")
        """
        # In production deployment, service identity is configured during service installation
        # Common identities: LocalService, NetworkService, or a gMSA
        # For this architecture, we recommend LocalService with appropriate ACL configuration
        return "LocalService"
    
    def get_service_key_storage_path(self) -> Path:
        """Get service-scoped key storage path.
        
        F14 V4-r9 FIX: Private key stored in service-scoped location.
        
        The key storage should be:
        - Protected by ACL allowing only service identity read/write
        - Located in machine-level directory (e.g., C:\\ProgramData\\IABV\\authority_keys\\)
        - Inaccessible to normal user process
        
        Returns:
            Path to service-scoped key storage directory
        """
        # Machine-level directory with service-only ACL
        # This is configured during service installation
        return Path("C:\\ProgramData\\IABV\\authority_keys")
    
    def get_named_pipe_name(self) -> str:
        """Get Named Pipe name for authority IPC.
        
        F14 V4-r9 FIX: Named Pipe with ACL restriction to authorized callers.
        
        Returns:
            Named Pipe name (e.g., r"\\\\.\\pipe\\IABVAuditAuthority")
        """
        return r"\\.\pipe\IABVAuditAuthority"
    
    def verify_service_installation(self) -> dict[str, Any]:
        """Verify if service is installed and configured correctly.
        
        F14 V4-r9 FIX: Verify service installation status.
        
        Returns:
            Status dictionary with installation state
        """
        if not WINDOWS_SERVICE_AVAILABLE:
            return {
                "installed": False,
                "error": "pywin32 not available",
            }
        
        try:
            # Check if service exists
            hscm = win32service.OpenSCManager(None, None, win32service.SC_MANAGER_CONNECT)
            try:
                hservice = win32service.OpenService(
                    hscm,
                    self.service_name,
                    win32service.SERVICE_QUERY_STATUS
                )
                try:
                    status = win32service.QueryServiceStatus(hservice)
                    return {
                        "installed": True,
                        "service_name": self.service_name,
                        "current_state": status[1],
                        "status": "running" if status[1] == win32service.SERVICE_RUNNING else "stopped",
                    }
                finally:
                    win32service.CloseServiceHandle(hservice)
            except win32service.error as exc:
                if exc.winerror == 1060:  # Service does not exist
                    return {
                        "installed": False,
                        "service_name": self.service_name,
                        "error": "Service not installed",
                    }
                raise
            finally:
                win32service.CloseServiceHandle(hscm)
        except Exception as exc:
            logger.error("Failed to verify service installation: %s", exc)
            return {
                "installed": False,
                "error": str(exc),
            }
    
    def get_installation_instructions(self) -> str:
        """Get instructions for installing the service.
        
        F14 V4-r9 FIX: Document service installation requirements.
        
        Returns:
            Installation instructions as string
        """
        return f"""
Windows Service Installation Instructions for {self.service_name}
======================================================================

Prerequisites:
1. Run as Administrator
2. pywin32 installed: pip install pywin32
3. Service executable path configured

Installation Commands (PowerShell - Administrator):
---------------------------------------------------
# Install service
python -m {self.__class__.__module__} install

# Start service
python -m {self.__class__.__module__} start

# Stop service
python -m {self.__class__.__module__} stop

# Remove service
python -m {self.__class__.__module__} remove

Service Configuration:
----------------------
- Service Name: {self.service_name}
- Display Name: {self.service_display_name}
- Description: {self.service_description}
- Recommended Identity: LocalService
- Key Storage: {self.get_service_key_storage_path()}
- Named Pipe: {self.get_named_pipe_name()}

ACL Configuration:
-------------------
After installation, configure ACLs:
1. Key storage directory: Full Control for service identity only
2. Named Pipe: Read/Write for authorized callers only
3. Trust anchor: Admin/System write, Users read

Security Boundary:
-----------------
- Service runs under dedicated identity (separate from normal user)
- Private key accessible only to service identity
- Normal user process cannot access service key storage
- IPC validates caller identity before authorizing operations

Status:
-------
Service Installation Required: YES
Current Installation Status: {self.verify_service_installation()}
"""


# Stub for service class when pywin32 is not available
if not WINDOWS_SERVICE_AVAILABLE:
    class AuthorityServiceHandler:
        """Stub service handler when pywin32 is not available."""
        
        def __init__(self, *args, **kwargs):
            raise RuntimeError(
                "Windows Service requires pywin32. "
                "Install with: pip install pywin32"
            )
else:
    class AuthorityServiceHandler(win32serviceutil.ServiceFramework):
        """Actual Windows Service handler for audit authority.
        
        F14 V4-r9 FIX: Service framework for running authority as Windows Service.
        
        This class is a subclass of win32serviceutil.ServiceFramework and
        implements the service lifecycle (start, stop, SvcDoRun).
        
        To use this as a real service, it must be registered with
        Windows Service Control Manager via service installation.
        """
        
        _svc_name_ = "IABVAuditAuthority"
        _svc_display_name_ = "IABV Audit Authority Service"
        _svc_description_ = "Cryptographic audit authority for IABV provenance verification"
        
        def __init__(self, args):
            win32serviceutil.ServiceFramework.__init__(self, args)
            self.hWaitStop = win32event.CreateEvent(None, 0, 0, None)
            logger.info("AuthorityServiceHandler initialized")
        
        def SvcStop(self):
            """Handle service stop."""
            self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
            win32event.SetEvent(self.hWaitStop)
            logger.info("AuthorityServiceHandler stopping")
        
        def SvcDoRun(self):
            """Main service loop.
            
            F14 V4-r9.4 FIX: Load authority key, verify identity, start IPC.
            Provisioning controlled by AUTHORITY_PROVISIONING_ENABLED flag file in C:\ProgramData\IABV\.
            Only Administrators can create this flag file, preventing normal users from enabling provisioning.
            """
            logger.info("AuthorityServiceHandler running")
            servicemanager.LogMsg(
                servicemanager.EVENTLOG_INFORMATION,
                servicemanager.PYS_SERVICE_STARTED,
                (self._svc_name_, "")
            )
            
            # F14 V4-r9.4 FIX: Initialize key manager
            key_manager = None
            pipe_server = None
            
            try:
                # Step 1: Initialize key manager
                key_storage_path = Path("C:\\ProgramData\\IABV\\authority_keys")
                program_data_path = Path("C:\\ProgramData\\IABV")
                key_manager = AuthorityKeyManager(
                    key_storage_path=key_storage_path,
                    service_identity="LocalService",
                    program_data_path=program_data_path
                )
                logger.info("Key manager initialized")
                
                # Step 2: Load authority key (fail-closed if missing unless provisioning flag exists)
                try:
                    key_manager.load_key()
                    logger.info("Authority key loaded successfully")
                except AuthorityKeyError as exc:
                    logger.error("Failed to load authority key: %s", exc)
                    logger.error("Service cannot operate without a valid key. Provisioning must create the key first.")
                    logger.error("To enable provisioning, create AUTHORITY_PROVISIONING_ENABLED flag in C:\\ProgramData\\IABV\\ as Administrator.")
                    self.ReportServiceStatus(win32service.SERVICE_STOPPED, win32service.ERROR_SERVICE_SPECIFIC_ERROR)
                    return
                
                # Step 3: Create Named Pipe server with key manager
                pipe_server = AuthorityNamedPipeServer(
                    pipe_name=r"\\.\pipe\IABVAuditAuthority",
                    authorized_sids=None,  # Will auto-detect during installation
                    key_manager=key_manager
                )
                pipe_server.start()
                logger.info("Named Pipe server started with authority key")
                
                # Step 4: Report service as ready
                self.ReportServiceStatus(win32service.SERVICE_RUNNING)
                logger.info("Authority service ready")
                
                # Step 5: Wait for stop signal
                win32event.WaitForSingleObject(self.hWaitStop, win32event.INFINITE)
                
            except Exception as exc:
                logger.error("Service main loop error: %s", exc)
                self.ReportServiceStatus(win32service.SERVICE_STOPPED, win32service.ERROR_SERVICE_SPECIFIC_ERROR)
            finally:
                # Stop Named Pipe server
                if pipe_server:
                    pipe_server.stop()
                    logger.info("Named Pipe server stopped")
            
            logger.info("AuthorityServiceHandler stopped")


def install_service(service_name: str = "IABVAuditAuthority", exe_path: str | None = None) -> None:
    """Install the Windows Service (requires Administrator).
    
    F14 V4-r9.5 FIX: Support custom exe_path for machine-scoped runtime.
    
    Args:
        service_name: Service name to install
        exe_path: Optional custom path to pythonservice.exe (e.g., for machine-scoped runtime)
    """
    if not WINDOWS_SERVICE_AVAILABLE:
        raise RuntimeError("pywin32 required for service installation")
    
    try:
        # Python class string: module.ClassName
        python_class_string = "iabv_v15.services.development.authority_windows_service.AuthorityServiceHandler"
        
        win32serviceutil.InstallService(
            python_class_string,  # First arg is pythonClassString, NOT exe_path
            service_name,
            "IABV Audit Authority Service",
            startType=win32service.SERVICE_AUTO_START,
            userName="NT AUTHORITY\\LocalService",
            password=None,
            exeName=exe_path,  # exe_path goes here as named parameter
            description="Cryptographic audit authority for IABV provenance verification"
        )
        logger.info("Service installed: %s (as LocalService, exe=%s)", service_name, exe_path or "default")
    except Exception as exc:
        logger.error("Failed to install service: %s", exc)
        raise


def remove_service(service_name: str = "IABVAuditAuthority") -> None:
    """Remove the Windows Service (requires Administrator).
    
    Args:
        service_name: Service name to remove
    """
    if not WINDOWS_SERVICE_AVAILABLE:
        raise RuntimeError("pywin32 required for service removal")
    
    try:
        win32serviceutil.RemoveService(service_name)
        logger.info("Service removed: %s", service_name)
    except Exception as exc:
        logger.error("Failed to remove service: %s", exc)
        raise


def start_service(service_name: str = "IABVAuditAuthority") -> None:
    """Start the Windows Service (requires Administrator).
    
    Args:
        service_name: Service name to start
    """
    if not WINDOWS_SERVICE_AVAILABLE:
        raise RuntimeError("pywin32 required for service control")
    
    try:
        win32serviceutil.StartService(service_name)
        logger.info("Service started: %s", service_name)
    except Exception as exc:
        logger.error("Failed to start service: %s", exc)
        raise


def stop_service(service_name: str = "IABVAuditAuthority") -> None:
    """Stop the Windows Service (requires Administrator).
    
    Args:
        service_name: Service name to stop
    """
    if not WINDOWS_SERVICE_AVAILABLE:
        raise RuntimeError("pywin32 required for service control")
    
    try:
        win32serviceutil.StopService(service_name)
        logger.info("Service stopped: %s", service_name)
    except Exception as exc:
        logger.error("Failed to stop service: %s", exc)
        raise


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        command = sys.argv[1].lower()
        
        if command == "install":
            exe_path = sys.argv[2] if len(sys.argv) > 2 else None
            install_service(exe_path=exe_path)
        elif command == "remove":
            remove_service()
        elif command == "start":
            start_service()
        elif command == "stop":
            stop_service()
        else:
            print("Usage: python authority_windows_service.py [install|remove|start|stop] [exe_path]")
    else:
        # Run as service (when launched by Service Control Manager)
        if WINDOWS_SERVICE_AVAILABLE:
            servicemanager.Initialize()
            servicemanager.PrepareToHostSingle(AuthorityServiceHandler)
            servicemanager.StartServiceCtrlDispatcher()
        else:
            print("pywin32 required for service execution")
